const DEV_URL = process.env.REACT_APP_DEV_URL;
const API_SERVICE_URL = process.env.REACT_APP_API_SERVICE_URL;
const PRO_URL = process.env.REACT_APP_PRO_URL;
const BASE_URL = process.env.REACT_APP_BASE_URL;
const APP_ID = process.env.REACT_APP_APP_ID;
const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.REACT_APP_GOOGLE_CLIENT_SECRET;

export {
  DEV_URL,
  API_SERVICE_URL,
  PRO_URL,
  BASE_URL,
  APP_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID
};
